Use samesite config setting value
iMerica/dj-rest-auth pull request #436
Opened 2022-09-29 19:16 UTC by Dresdn

Uses the `settings.JWT_AUTH_SAMESITE` value when deleting cookies, maintaining the consistency of how the cookies were created.

Closes #435

2022-10-18 07:43 UTC, whoismaruf requested changes
Good changes 🤝

2022-11-24 22:18 UTC, loomitz commented
Thanks, works as expected. This changes correctly cleans cookies when /logout is used

2023-01-02 22:17 UTC, iMerica approved these changes

2023-01-02 22:17 UTC, iMerica commented
Thank you for submitting this PR and apologies for the delay.

2023-01-02 22:17 UTC, merged