Modify JWT Serializer Field Names
iMerica/dj-rest-auth pull request #501
Opened 2023-04-14 21:21 UTC by Dresdn

Closes #142 

This change modifies the `JWTSerializer` fields to be `access` and `response` to align with the naming of [rest_framework_jwt.serializers.TokenRefreshSerializer](https://github.com/jazzband/djangorestframework-simplejwt/blob/master/rest_framework_simplejwt/serializers.py#L102)

With `rest_framework_simplejwt` being tightly coupled into the JWT usage, this made sense to adhere to the upstream dependency naming standards.

Ultimately, it's ugly when using JWT to check for `access_token` names when authenticating, and then using `access` for a refresh.

2023-04-14 23:21 UTC, zackkh commented
Greetings ! While you're at it, can you add `refresh_expiration` field to [dj_rest_auth.jwt_auth.get_refresh_view](https://github.com/iMerica/dj-rest-auth/blob/master/dj_rest_auth/jwt_auth.py#L88)'s response data  since we are already returning an access expiration timestamp ?

```
def get_refresh_view():
    """ Returns a Token Refresh CBV without a circular import """
    from rest_framework_simplejwt.settings import api_settings as jwt_settings
    from rest_framework_simplejwt.views import TokenRefreshView

    class RefreshViewWithCookieSupport(TokenRefreshView):
        serializer_class = CookieTokenRefreshSerializer

        def finalize_response(self, request, response, *args, **kwargs):
            if response.status_code == status.HTTP_200_OK and 'access' in response.data:
                set_jwt_access_cookie(response, response.data['access'])
                response.data['access_expiration'] = (timezone.now() + jwt_settings.ACCESS_TOKEN_LIFETIME)
            if response.status_code == status.HTTP_200_OK and 'refresh' in response.data:
                set_jwt_refresh_cookie(response, response.data['refresh'])
                response.data['refresh_expiration'] = (timezone.now() + jwt_settings.REFRESH_TOKEN_LIFETIME)
            return super().finalize_response(request, response, *args, **kwargs)
    return RefreshViewWithCookieSupport
```

2023-04-14 23:26 UTC, zackkh requested changes
Greetings ! While you're at it, can you add `refresh_expiration` field to [dj_rest_auth.jwt_auth.get_refresh_view](https://github.com/iMerica/dj-rest-auth/blob/master/dj_rest_auth/jwt_auth.py#L88)'s response data since we are already returning an access expiration timestamp ?

```
def get_refresh_view():
    """ Returns a Token Refresh CBV without a circular import """
    from rest_framework_simplejwt.settings import api_settings as jwt_settings
    from rest_framework_simplejwt.views import TokenRefreshView

    class RefreshViewWithCookieSupport(TokenRefreshView):
        serializer_class = CookieTokenRefreshSerializer

        def finalize_response(self, request, response, *args, **kwargs):
            if response.status_code == status.HTTP_200_OK and 'access' in response.data:
                set_jwt_access_cookie(response, response.data['access'])
                response.data['access_expiration'] = (timezone.now() + jwt_settings.ACCESS_TOKEN_LIFETIME)
            if response.status_code == status.HTTP_200_OK and 'refresh' in response.data:
                set_jwt_refresh_cookie(response, response.data['refresh'])
                response.data['refresh_expiration'] = (timezone.now() + jwt_settings.REFRESH_TOKEN_LIFETIME)
            return super().finalize_response(request, response, *args, **kwargs)
    return RefreshViewWithCookieSupport
```

2023-04-15 16:30 UTC, Dresdn commented
Good call @zackkh. I saw that but didn't dawn on me to include it. Let me know if there's anything else to be done.

2023-04-15 16:39 UTC, zackkh approved these changes
Changes are 5/5 and match up with `djangorestframework-simplejwt`.

2023-05-07 05:30 UTC, iMerica approved these changes

2023-05-07 05:31 UTC, merged